### ISSUE TITLE
Ruby 3.1.1

### ISSUE THREAD

**Issue by richardrails** [lostisland/faraday-multipart#10]
I am getting the warning:
```
/home/.../gems/faraday-multipart-1.0.4/lib/faraday/multipart.rb:17: warning: already initialized constant Faraday::Parts
/home/.../gems/faraday-0.17.5/lib/faraday/upload_io.rb:66: warning: previous definition of Parts was here
/home/.../gems/ruby-3.1.1/gems/faraday-multipart-1.0.4/lib/faraday/multipart.rb:18: warning: already initialized constant Faraday::CompositeReadIO
/home/.../gems/ruby-3.1.1/gems/faraday-0.17.5/lib/faraday/upload_io.rb:12: warning: previous definition of CompositeReadIO was here
/home/.../gems/ruby-3.1.1/gems/faraday-multipart-1.0.4/lib/faraday/multipart.rb:21: warning: already initialized constant Faraday::UploadIO
/home/.../gems/ruby-3.1.1/gems/faraday-0.17.5/lib/faraday/upload_io.rb:65: warning: previous definition of UploadIO was here
```
**ruby 3.1.1
faraday v.0.17.5
faraday-multipart v.1.0.4**

Can you please make changes to get rid of that?

**Comment by anandvc** [comment]
I'm using `ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-linux]` and I see the same warnings there, so I'm not sure if this is related to the ruby version.

I'm not sure about my gem versions because I have multiple versions installed, but I believe I'm using **faraday 1.5.1** and **faraday-multipart 1.0.4**.

**Comment by olleolleolle** [comment]
Seems like the `multipart.rb` file is trying to do the same job that this file is doing (better):

https://github.com/lostisland/faraday-multipart/blob/main/lib/faraday/multipart/file_part.rb#L53-L62

**Comment by iMacTia** [comment]
`faraday-multipart` is only needed with Faraday 1.9.0+
Before then, it was part of Faraday itself.
What's happening is that both gems (`faraday` and `faraday-multipart`) are defining the same constants.

I'm not sure why this is happening, but you might have `faraday-multipart` in your Gemfile or it may be coming from another dependency. If it's the former, then you can simply remove it from the Gemfile.

If it's the latter, you'll need to reach out to the gem that is pulling `faraday-multipart` into your bundle
