### ISSUE TITLE
Image is not saving with post request

### ISSUE THREAD

**Issue by kashiftufail** [lostisland/faraday-multipart#11]
I have author class using active storage. 

                  class Author < ApplicationRecord
                      has_one_attached :image
                  end     

post request

                 require 'faraday'
                 require 'faraday/multipart'

                 payload = { author: {title: "lo"} }
                 payload[:author][:image] = Faraday::Multipart::FilePart.new(File.open(Rails.root.join('app', 'assets', 'images', 'about.jpg')), 'image/jpeg')

                 conn.post('/api/v1/authors', payload.to_json)

My received params

             #<ActionController::Parameters {"author"=>{"title"=>"lo"}, "image"=>{"content_type"=>"image/jpeg", 
             "original_filename"=>"local.path", "local_path"=>"local.path", 
              "io"=>"/home/kashif/ticket_plot_api/app/assets/images/about.jpg", "opts"=>{}}, "controller"=>"api/v1/authors", 
               "action"=>"create"} permitted: false>

Author is saving without image

Is anything wrong?
Thanks

**Comment by iMacTia** [comment]
Hi @kashiftufail,
it would be useful to see your Faraday connection as well (i.e. how you instantiate `conn`), but at a first glance I can see you're calling `#to_json`. That might be the problem, can you try removing it and just call `conn.post('/api/v1/authors', payload.to_json)`

**Comment by kashiftufail** [comment]
Here is my faraday connection

     conn = Faraday.new(
        url: 'http://localhost:3000/',      
        headers: {'Content-Type' => 'application/json','Authorization' => "Bearer qAJiTqIJRou0"}    )      do   |f|

            f.request :multipart
            f.adapter :net_http

        end 

If i remove  to_json like below

       conn.post('/api/v1/authors', payload)

Then this error occurs

        undefined method `bytesize' for {:author=>{:title=>"foo", :full_name=>"tony", :image=># 
              <Multipart::Post::UploadIO:0x00007f78f4762310 @content_type="image/jpeg", @original_filename="about.jpg", 
             @local_path="/home/kashif/ticket_plot_api/app/assets/images/about.jpg", @io=# 
             <File:/home/kashif/ticket_plot_api/app/assets/images/about.jpg>, @opts={}>}}:Hash

**Comment by iMacTia** [comment]
Thank you for the additional details @kashiftufail.
The problem I see here is that you're trying to mix a multipart payload with a JSON request.
My guess is that you want to make a `www-form-urlencoded` request instead.

You could try with the following:

```ruby
# Note no Content-Type header, only Authorization
conn = Faraday.new(url: 'http://localhost:3000/', headers: { 'Authorization' => "Bearer ..." }) do |f|
  f.request :multipart
  f.request :url_encoded # adding this to send a www-form-urlencoded request
  f.adapter :net_http
end

payload = ... # Payload should be fine as it is

conn.post('/api/v1/authors', payload)
```

**Comment by kashiftufail** [comment]
Thanks for your response @iMacTia 

But i still getting error same error if i call like

             conn.post('/api/v1/authors', payload) # without payload.to_json
 
error           

                 undefined method `bytesize' for {:author=>{:title=>"lo g", :image=>#<Multipart::Post::UploadIO:0x00007f57f1c9a450 
                @content_type="image/jpeg", @original_filename="about.jpg", 
                @local_path="/home/kashif/ticket_plot_api/app/assets/images/about.jpg", @io=# 
                <File:/home/kashif/ticket_plot_api/app/assets/images/about.jpg>, @opts={}>}}:Hash

call like below

                 conn.post('/api/v1/authors', payload.to_json) 

save author record in db without image. but i want save author as well as image.

Any idea?

**Comment by kashiftufail** [comment]
i just remove  "Content-Type' => 'application/json" from header. This was issue
   
         headers: {'Authorization' => "Bearer qAJiTqIJRou0"}    

And working.

Thanks @iMacTia
