### ISSUE TITLE
Deprection Warning message ::MultipartPost is deprecated on multipart-post(2.4.1)

### ISSUE THREAD

**Issue by diogolsq** [lostisland/faraday-multipart#15]
### Context 
[after the release of version 2.4.1 of **multipart-post** in May 07,2024](https://rubygems.org/gems/multipart-post)
 the version 1.0.4 generates a deprecation warning due to its usage of the top-level `::MultipartPost` constant which is now deprecated

**Comment by olleolleolle** [comment]
The upcoming version depends on gems, a3609a6, in order to avoid that. Pending a release.

**Comment by diogolsq** [comment]
I am closing this issue because it is not related to faraday-multipart.

The message `Top level ::MultipartPost is deprecated, require 'multipart/post' and use Multipart::Post instead!`
does not stem from your library. After reviewing your `lib/faraday/multipart/version.rb`, I realize this issue originates from a recently added dependency that introduced the outdated call.

Sorry  for the confusion and for raising this issue in error.
